export const FEATURE_COSTS = {
  POST_MATCH: 5,
  BOOST_PORTFOLIO: 50,
  TOURNAMENT_ENTRY: 100,
  PRO_SUBSCRIPTION: 500,
  GOLD_SUBSCRIPTION: 1500,
  CONNECTION_REQUEST: 10,
  VOICE_CHANNEL_PREMIUM: 200,
} as const;

export const AD_REWARDS = {
  REWARDED_AD: 5,
  BONUS_AD: 10,
  DOUBLE_REWARD: 10,
} as const;
